# Generated by Django 3.2 on 2021-04-28 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilmList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=20)),
                ('url', models.URLField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='film/film/%Y/%m/%d')),
                ('context', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
