# Generated by Django 3.2 on 2021-05-24 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nickname',
            new_name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='social',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
