# Generated by Django 3.2 on 2021-07-05 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModelExtend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hit', models.IntegerField(default=0)),
                ('like_user_set', models.ManyToManyField(blank=True, related_name='like_BaseModelExtend_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hit', models.IntegerField(default=0)),
                ('rate', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1)),
                ('message', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CommentFreeBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hit', models.IntegerField(default=0)),
                ('message', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentHirePostActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hit', models.IntegerField(default=0)),
                ('message', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentHirePostStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hit', models.IntegerField(default=0)),
                ('message', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagFreeBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagPostActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagPostStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagResumeActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagResumeStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='QnA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateTimeField()),
                ('context', models.TextField()),
                ('is_done', models.BooleanField()),
                ('upload', models.FileField(blank=True, upload_to='Qna/%Y/%m/%d')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentInCommentHirePostStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hit', models.IntegerField(default=0)),
                ('message', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CommentInCommentHirePostStaff', to='film.commenthirepoststaff')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CommentInCommentHirePostActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hit', models.IntegerField(default=0)),
                ('message', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CommentInCommentHirePostActor', to='film.commenthirepostactor')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CommentInCommentFreeBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hit', models.IntegerField(default=0)),
                ('message', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CommentInCommentFreeBoard', to='film.commentfreeboard')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CommentInComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hit', models.IntegerField(default=0)),
                ('message', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CommentInComment', to='film.comment')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ResumeStaff',
            fields=[
                ('basemodelextend_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='film.basemodelextend')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='Resume/Staff/image/%Y/%m/%d')),
                ('upload', models.FileField(blank=True, upload_to='Resume/Staff/upload/%Y/%m/%d')),
                ('title', models.CharField(max_length=50)),
                ('tel', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('context', models.TextField()),
                ('category', models.CharField(choices=[('촬영', '촬영'), ('연출', '연출'), ('시나리오', '시나리오'), ('음악', '음악')], max_length=10)),
                ('resume_url', models.URLField(blank=True)),
                ('is_publish', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tag_set', models.ManyToManyField(blank=True, to='film.TagResumeStaff')),
            ],
            options={
                'abstract': False,
            },
            bases=('film.basemodelextend',),
        ),
        migrations.CreateModel(
            name='ResumeActor',
            fields=[
                ('basemodelextend_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='film.basemodelextend')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('height', models.IntegerField()),
                ('gender', models.CharField(choices=[('남자', '남자'), ('여자', '여자')], max_length=4)),
                ('resume_url', models.URLField(blank=True)),
                ('context', models.TextField()),
                ('agency', models.CharField(blank=True, max_length=50)),
                ('career', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('아역', '아역'), ('청소년', '청소년'), ('성인', '성인'), ('중장년', '중장년')], max_length=10)),
                ('image', models.ImageField(upload_to='Resume/Actor/image/%Y/%m/%d')),
                ('upload', models.FileField(blank=True, upload_to='Resume/Actor/upload/%Y/%m/%d')),
                ('tel', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_publish', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tag_set', models.ManyToManyField(blank=True, to='film.TagResumeActor')),
            ],
            options={
                'abstract': False,
            },
            bases=('film.basemodelextend',),
        ),
        migrations.CreateModel(
            name='HirePostStaff',
            fields=[
                ('basemodelextend_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='film.basemodelextend')),
                ('thumbs', models.IntegerField(blank=True, default=0)),
                ('category', models.CharField(choices=[('영화', '영화'), ('드라마', '드라마'), ('뮤직비디오', '뮤직비디오'), ('광고', '광고')], max_length=10)),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='HirePost/Staff/image/%Y/%m/%d')),
                ('upload', models.FileField(blank=True, upload_to='HirePost/Staff/upload/%Y/%m/%d')),
                ('company', models.CharField(max_length=20)),
                ('company_loca', models.CharField(blank=True, max_length=50)),
                ('company_desc', models.TextField()),
                ('company_url', models.URLField(blank=True)),
                ('job_position', models.CharField(max_length=50)),
                ('context', models.TextField()),
                ('requirement', models.TextField()),
                ('advantage', models.TextField(blank=True)),
                ('job_loca', models.CharField(blank=True, max_length=100)),
                ('deadline', models.DateTimeField()),
                ('manager', models.CharField(max_length=10)),
                ('payment', models.IntegerField()),
                ('wage_choice', models.CharField(blank=True, choices=[('시급', '시급'), ('일급', '일급'), ('주급', '주급'), ('월급', '월급')], max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to=settings.AUTH_USER_MODEL)),
                ('is_applied_set', models.ManyToManyField(blank=True, related_name='staff_is_applied_set', to=settings.AUTH_USER_MODEL)),
                ('tag_set', models.ManyToManyField(blank=True, to='film.TagPostStaff')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=('film.basemodelextend',),
        ),
        migrations.CreateModel(
            name='HirePostActor',
            fields=[
                ('basemodelextend_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='film.basemodelextend')),
                ('thumbs', models.IntegerField()),
                ('category', models.CharField(choices=[('영화', '영화'), ('드라마', '드라마'), ('뮤직비디오', '뮤직비디오'), ('광고', '광고')], max_length=10)),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='HirePost/Actor/image/%Y/%m/%d')),
                ('upload', models.FileField(blank=True, upload_to='HirePost/Actor/%Y/upload/%m/%d')),
                ('company', models.CharField(max_length=20)),
                ('company_loca', models.CharField(blank=True, max_length=50)),
                ('company_desc', models.TextField()),
                ('company_url', models.URLField(blank=True)),
                ('job_position', models.CharField(max_length=50)),
                ('context', models.TextField()),
                ('requirement', models.TextField()),
                ('advantage', models.TextField(blank=True)),
                ('job_loca', models.CharField(blank=True, max_length=100)),
                ('deadline', models.DateTimeField()),
                ('payment', models.IntegerField()),
                ('manager', models.CharField(max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('is_applied_set', models.ManyToManyField(blank=True, related_name='actor_is_applied_set', to=settings.AUTH_USER_MODEL)),
                ('tag_set', models.ManyToManyField(blank=True, to='film.TagPostActor')),
            ],
            options={
                'abstract': False,
            },
            bases=('film.basemodelextend',),
        ),
        migrations.CreateModel(
            name='FreeBoard',
            fields=[
                ('basemodelextend_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='film.basemodelextend')),
                ('category', models.CharField(choices=[('정보공유', '정보공유'), ('일상', '일상'), ('잡담', '잡담')], max_length=10)),
                ('title', models.CharField(max_length=50)),
                ('context', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='freeboard/%Y/%m/%d')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tag_set', models.ManyToManyField(blank=True, to='film.TagFreeBoard')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=('film.basemodelextend',),
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('basemodelextend_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='film.basemodelextend')),
                ('title', models.CharField(max_length=20)),
                ('url', models.URLField(blank=True)),
                ('context', models.TextField()),
                ('country', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=10)),
                ('actors', models.CharField(blank=True, max_length=100)),
                ('staffs', models.CharField(blank=True, max_length=100)),
                ('is_picked', models.BooleanField(default=False)),
                ('on_streaming', models.BooleanField(default=False)),
                ('grade', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, upload_to='film/%Y/%m/%d')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_film_set', to=settings.AUTH_USER_MODEL)),
                ('genre_set', models.ManyToManyField(blank=True, to='film.Genre')),
                ('tag_set', models.ManyToManyField(blank=True, to='film.TagFilm')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=('film.basemodelextend',),
        ),
        migrations.AddField(
            model_name='commenthirepoststaff',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CommentHirePostStaff', to='film.hirepoststaff'),
        ),
        migrations.AddField(
            model_name='commenthirepostactor',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CommentHirePostActor', to='film.hirepostactor'),
        ),
        migrations.AddField(
            model_name='commentfreeboard',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CommentFreeBoard', to='film.freeboard'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comment', to='film.film'),
        ),
    ]
