# Generated by Django 3.2 on 2021-04-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('dates', models.DateField(auto_now=True)),
                ('thumb', models.IntegerField()),
                ('url', models.URLField()),
                ('context', models.TextField()),
                ('director', models.CharField(max_length=10)),
                ('genre', models.CharField(max_length=10)),
            ],
        ),
    ]
