# Generated by Django 3.2.2 on 2021-06-03 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='image',
            field=models.ImageField(blank=True, upload_to='film/%Y/%m/%d'),
        ),
    ]
