# Generated by Django 3.2 on 2021-04-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hire_Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('dt_write', models.DateField(auto_now_add=True)),
                ('dt_mod', models.DateField(auto_now_add=True)),
                ('pic', models.ImageField(null=True, upload_to='')),
                ('requirement', models.TextField()),
                ('prefer', models.TextField(null=True)),
                ('location', models.CharField(max_length=30)),
                ('fee', models.IntegerField()),
                ('review', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_C',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User_I',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=8)),
            ],
        ),
    ]
