# Generated by Django 3.2.2 on 2021-05-20 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hirepoststaff',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='resumeactor',
            name='gender',
            field=models.CharField(choices=[('남자', '남자'), ('여자', '여자')], default='남자', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hirepoststaff',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to=settings.AUTH_USER_MODEL),
        ),
    ]
