# Generated by Django 3.2 on 2021-05-24 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qna',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentincommenthirepoststaff',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentincommenthirepoststaff',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.commenthirepoststaff'),
        ),
        migrations.AddField(
            model_name='commentincommenthirepostactor',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentincommenthirepostactor',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.commenthirepostactor'),
        ),
        migrations.AddField(
            model_name='commentincommentfreeboard',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentincommentfreeboard',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.commentfreeboard'),
        ),
        migrations.AddField(
            model_name='commentincomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentincomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.comment'),
        ),
        migrations.AddField(
            model_name='commenthirepoststaff',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commenthirepostactor',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentfreeboard',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='basemodelextend',
            name='like_user_set',
            field=models.ManyToManyField(blank=True, related_name='like_BaseModelExtend_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resumestaff',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resumestaff',
            name='tag_set',
            field=models.ManyToManyField(blank=True, to='film.TagResumeStaff'),
        ),
        migrations.AddField(
            model_name='resumeactor',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resumeactor',
            name='tag_set',
            field=models.ManyToManyField(blank=True, to='film.TagResumeActor'),
        ),
        migrations.AddField(
            model_name='hirepoststaff',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hirepoststaff',
            name='tag_set',
            field=models.ManyToManyField(blank=True, to='film.TagPostStaff'),
        ),
        migrations.AddField(
            model_name='hirepostactor',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hirepostactor',
            name='tag_set',
            field=models.ManyToManyField(blank=True, to='film.TagPostActor'),
        ),
        migrations.AddField(
            model_name='freeboard',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='freeboard',
            name='tag_set',
            field=models.ManyToManyField(blank=True, to='film.TagFreeBoard'),
        ),
        migrations.AddField(
            model_name='film',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_film_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='film',
            name='genre_set',
            field=models.ManyToManyField(blank=True, to='film.Genre'),
        ),
        migrations.AddField(
            model_name='film',
            name='tag_set',
            field=models.ManyToManyField(blank=True, to='film.TagFilm'),
        ),
        migrations.AddField(
            model_name='commenthirepoststaff',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.hirepoststaff'),
        ),
        migrations.AddField(
            model_name='commenthirepostactor',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.hirepostactor'),
        ),
        migrations.AddField(
            model_name='commentfreeboard',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.freeboard'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.film'),
        ),
    ]
