# Generated by Django 3.2 on 2021-05-01 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_faq'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Faq',
            new_name='Support',
        ),
    ]
