# Generated by Django 3.2.2 on 2021-05-20 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_auto_20210520_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hirepostactor',
            old_name='detail',
            new_name='context',
        ),
    ]
