# Generated by Django 3.1.6 on 2021-05-09 03:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('film', '0004_auto_20210503_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagPostActor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagPostStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagResumeActor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagResumeStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Tag',
            new_name='TagFilm',
        ),
        migrations.RemoveField(
            model_name='film',
            name='photo',
        ),
        migrations.CreateModel(
            name='ResumeStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
                ('upload', models.FileField(blank=True, upload_to='')),
                ('title', models.CharField(max_length=50)),
                ('tel', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('context', models.TextField()),
                ('resume_url', models.URLField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tag_set', models.ManyToManyField(blank=True, to='film.TagResumeStaff')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResumeActor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('resume_url', models.URLField(blank=True)),
                ('context', models.TextField()),
                ('agency', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(upload_to='Resume/Actor/%Y/%m/%d')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tag_set', models.ManyToManyField(blank=True, to='film.TagResumeActor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QnA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateTimeField()),
                ('context', models.TextField()),
                ('is_done', models.BooleanField()),
                ('upload', models.FileField(blank=True, upload_to='Qna/%Y/%m/%d')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HirePostStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thumbs', models.IntegerField(blank=True)),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='HirePost/Staff/%Y/%m/%d')),
                ('company', models.CharField(max_length=20)),
                ('company_loca', models.CharField(blank=True, max_length=50)),
                ('company_desc', models.TextField()),
                ('company_url', models.URLField(blank=True)),
                ('job_position', models.CharField(max_length=50)),
                ('detail', models.TextField()),
                ('requirement', models.TextField()),
                ('advantage', models.TextField(blank=True)),
                ('job_loca', models.CharField(blank=True, max_length=100)),
                ('deadline', models.DateTimeField()),
                ('payment', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tag_set', models.ManyToManyField(blank=True, to='film.TagPostStaff')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HirePostActor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thumbs', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='HirePost/Actor/%Y/%m/%d')),
                ('company', models.CharField(max_length=20)),
                ('company_loca', models.CharField(blank=True, max_length=50)),
                ('company_desc', models.TextField()),
                ('company_url', models.URLField(blank=True)),
                ('job_position', models.CharField(max_length=50)),
                ('detail', models.TextField()),
                ('requirement', models.TextField()),
                ('advantage', models.TextField(blank=True)),
                ('job_loca', models.CharField(blank=True, max_length=100)),
                ('deadline', models.DateTimeField()),
                ('payment', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tag_set', models.ManyToManyField(blank=True, to='film.TagPostActor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FreeBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('context', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='freeboard/%Y/%m/%d')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
