# Generated by Django 3.2.2 on 2021-05-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0006_auto_20210509_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rate',
            field=models.IntegerField(default=1),
        ),
    ]
