# Generated by Django 3.2.2 on 2021-05-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0008_alter_comment_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='country',
            field=models.CharField(default='korea', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='film',
            name='is_picked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='film',
            name='on_streaming',
            field=models.BooleanField(default=False),
        ),
    ]
